# Generated by Django 4.1.1 on 2022-09-30 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('km_driven', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('is_acive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled')], default='pending', max_length=120)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_bikes.bikes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_bikes.bikes')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='b_user', to=settings.AUTH_USER_MODEL)),
                ('sale_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_bikes.offer')),
                ('saler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BikeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='bike_pics')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used_bikes.bikes')),
            ],
        ),
    ]
