# Generated by Django 4.1.1 on 2022-09-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('used_bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='is_acive',
            new_name='is_active',
        ),
    ]
